### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by prabhu** [lalalic/docx4js#1]
Hi,

Very interesting project. Whats the license?

Best,
Prabhu

**Comment by fab1an** [comment]
GPL, it says so in the package.json. Is there a way to relicense this, so I can use it commercially?

**Comment by lalalic** [comment]
Yes, it's possible to relicense it. how do you like it use it? and what kind of service do you want?

**Comment by mlockett42** [comment]
Current package.json says MIT Readme say GPL.

Which one is it?

In any case it is best practice to put a licence.txt file in the repo. The fsf makes a series of recommendations when using the GPL licence https://www.gnu.org/licenses/gpl-howto.html

**Comment by lalalic** [comment]
MIT
