### ISSUE TITLE
Uncaught (in promise) ReferenceError: DOCX is not defined in nodejs

### ISSUE THREAD

**Issue by ShawnLin013** [lalalic/docx4js#13]
Uncaught (in promise) ReferenceError: DOCX is not defined in nodejs

```
var docx4js = require("docx4js");
docx4js.load("my file path").then(function(doc){
    console.log(doc);
    var nothingFactory=DOCX.createVisitorFactory();
});
```

**Comment by maotora** [comment]
In this line:
`var nothingFactory=DOCX.createVisitorFactory();`
Where is `DOCX` defined exactly?
You seem to pass `(doc)` as a param but then reference `docx` or am I missing something?
Whats the logging of `console.log(doc)`?

**Comment by YangAlas** [comment]
@ShawnLin013 where is the file of `docx4js`，i can not find in the project, and no project named docx4js on `npm`,

**Comment by maotora** [comment]
@YangAlas  I ended up using [this](https://www.npmjs.com/package/docxtemplaterCopy)

**Comment by lalalic** [comment]
this project is docx4js :)
