### ISSUE TITLE
"officeDocument is not defined" when using ModelHandler

### ISSUE THREAD

**Issue by bcaure** [lalalic/docx4js#15]
When I declare   
`const ModelHandler = require("docx4js/lib/openxml/docx/model-handler").default;`
I have the following error with node 7.0.0 

> (node:7814) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): ReferenceError: officeDocument is not defined

In document.js line 63, there is a typo on `officeDocument.identify` should be `OfficeDocument.identify`

That's fixing the issue and then after that I have another error:

> TypeError: officeDocument.styles is not a function

**Comment by retorquere** [comment]
this fix indeed resolves the issue for me.

**Comment by ombogdanJoinToIt** [comment]
not yet

**Comment by teffy** [comment]
> not yet


I browsed the git commit history and found the following 2 commits that deleted dom-handler

https://github.com/lalalic/docx4js/commit/3cb7e25ac9dabd7f1b166b1375607f80e84433ad
https://github.com/lalalic/docx4js/commit/db71cfa37eef6eee26084792058c823a02e15d18

you can do it like this

```
const EventEmitter = require("events")

class DomHandler extends EventEmitter{
  createElement(type,props,children){
    return {type,props,children}
  }
}

docx4js.docx.load("test.docx").then(docx=>{
  const handler=new DomHandler()
  handler.on("*",function(type,props,children){
   // ……
  })
  handler.on("r",function(type,props,children){
   // ……
  })

  docx.parse(handler)
})
```
