### ISSUE TITLE
how to fetch total html content

### ISSUE THREAD

**Issue by chandulella23** [lalalic/docx4js#22]
var docx4js =require("docx4js")

docx4js.load("./abc.docx").then(docx=>{
	//you can render docx to anything (react elements, tree, dom, and etc) by giving a function
	docx.render(function createElement(type,props,children){
		return {type,props,children}

	})
})

if i type this code,it returns only props,children and it types. but i require total html content should be saved in any other variable or file .Is it possible to save entire parsed docx file in a variable which holds html content??

**Comment by welkinwong** [comment]
same

**Comment by lalalic** [comment]
if you are trying to convert docx to html, you can use docx2html.
