### ISSUE TITLE
In browser and documentation

### ISSUE THREAD

**Issue by natcohen** [lalalic/docx4js#3]
It looks very interesting and could be used for many applications but the documentation is almost non-existent so it makes it very difficult to use.

Would it be possible to adapt it to in-browser use?

**Comment by lalalic** [comment]
yes, it support node and browser

**Comment by fiatjaf** [comment]
How do I use it in the browser?

I have a string returned by GitHub when I request the raw contents of a `.docx` file. (see ` curl 'https://api.github.com/repos/lalalic/docx4js/contents/__tests__/files/loader.docx?ref=b132a61'` for a base64encoded response of that). Is it possible to use that as an input to docx4js?

**Comment by lalalic** [comment]
yes, it can use an input
