### ISSUE TITLE
still live?

### ISSUE THREAD

**Issue by Ethaan** [lalalic/docx4js#6]
Hi

this repo is still live?

im having some issues to install this package from a MeteorJs package, using odd npm.require, about a missing xmldom module.

this could be fixed, but im worried about if this library is still maintened for future bugs.

**Comment by lalalic** [comment]
yes, it's live

**Comment by rashmimhatre100** [comment]
Hi @Ethaan ,
I am trying to use this package with meteor but getting error,
Uncaught (in promise) TypeError: require(...).readFile is not a function.

Have you managed to get success using this package.
