### ISSUE TITLE
 Unexpected token return

### ISSUE THREAD

**Issue by SHocker-Yu** [lalalic/docx4js#7]
Hi,i used the example,

docx4j.load('./test.docx') // my file path in nodejs

error:
\docx4js.js:16
            return DOCX.createVisitorFactory(function(wordModel){
            ^^^^^^

SyntaxError: Unexpected token return
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3

**Comment by SHocker-Yu** [comment]
I found the example miss 's' at line 2 the word 'docx4j',and there are some brackets missed,could you help me to ues this package,I think it's the best for me.

**Comment by atnartur** [comment]
@SHocker-Yu sorry, I don't know that you already issue. Please attach some code before error line.

**Comment by SHocker-Yu** [comment]
I just use the example of this package's author supported in readme.
var docx4js=require("docx4js")
docx4js.load('test.docx') // a file path in nodejs
    .then(function(doc){
        var nothingFactory=DOCX.createVisitorFactory()

        var textFactory=(function(){
            var visitor=[]
            visitor.visit=(function(){
                switch(this.model.type){
                case 'paragraph':
                    return this.push("\n\r")
                case 'text':
                    return this.push(this.model.getText())
                }
            }
            return docx4js.createVisitorFactory(function(wordModel){
                visitor.model=wordModel
            })
        )();

        var complexFactory=(function(){
            class Visitor{}
            class P extends Visitor{
                visit(){}
            }
            class Image extends Visitor{
                visit(){}
            }
            class Shape extends Visitor{
                visit(){}
            }
            class Text extends Visitor{
                visit(){}
            }

            return DOCX.createVisitorFactory({
                    'paragraph': P,
                    'image': Image,
                    'text': Text,
                    'shape': Shape
                })
        )();

        doc.parse(nothingFactory, textFactory, complexFactory)
    })

**Comment by atnartur** [comment]
After this anonymous function shuold be a `)`. So final and fixed code will be:
```
visitor.visit=(function(){
            switch(this.model.type){
            case 'paragraph':
                return this.push("\n\r")
            case 'text':
                return this.push(this.model.getText())
            }
        }) // <-- added )
```

**Comment by atnartur** [comment]
I suggested a pull request #8 with this fix. I hope @lalalic will merge it.

**Comment by SHocker-Yu** [comment]
@atnartur  Thank you for your help,It's so nice of you.Would you use this example to do a test?
I found there is not just one `)` missed.

**Comment by atnartur** [comment]
I suggested fix with `s` letter in the second line. But @lalalic still ignore it. Where are other bugs?
