### ISSUE TITLE
no createVisitorFactory, parse behaves differently etc. - version 2.0.1

### ISSUE THREAD

**Issue by fercsi** [lalalic/docx4js#9]
Hi,

README.md is outdated or some files are missing from source. (Actually, there are several punctuation failures in example code, either)

1, There is no createVisitorFactory in docx4js. Actually, there is no such word in the whole project (only in README.md). I tried to find the way from source code, but I did not find the alternative.
2, Even function `parse` does not have any arguments.

I did not find any ways to use this lib.

**Comment by jmealo** [comment]
Confirmed:
https://github.com/lalalic/docx4js/search?utf8=%E2%9C%93&q=createVisitorFactory&type=

The mention is no longer in the README. Can we close this ticket @lalalic?

**Comment by lalalic** [comment]
updated in readme
